

all:
	$(MAKE) -C CmpEmiconEmu/Linux all
	$(MAKE) -C CmpEmiconEventsControl/Linux all
	$(MAKE) -C CmpEmiconLCD/Linux all

clean: cleanall

cleanall:
	$(MAKE) -C CmpEmiconEmu/Linux cleanall
	$(MAKE) -C CmpEmiconEventsControl/Linux cleanall
	$(MAKE) -C CmpEmiconLCD/Linux cleanall



