

all:
	$(MAKE) -C CmpEmiconEmu/Linux all
	$(MAKE) -C CmpEmiconEventsControl/Linux all
	$(MAKE) -C CmpEmiconLCD/Linux all
	$(MAKE) -C CmpEmiconLog/Linux all
	$(MAKE) -C CmpEmiconMemManager/Linux all
	$(MAKE) -C CmpEmiconNetwork/Linux all

clean: cleanall

cleanall:
	$(MAKE) -C CmpEmiconEmu/Linux cleanall
	$(MAKE) -C CmpEmiconEventsControl/Linux cleanall
	$(MAKE) -C CmpEmiconLCD/Linux cleanall
	$(MAKE) -C CmpEmiconLog/Linux cleanall
	$(MAKE) -C CmpEmiconMemManager/Linux cleanall
	$(MAKE) -C CmpEmiconNetwork/Linux cleanall



