#!/bin/sh

LOGFILE=/tmp/codesyscontrol.log
CODESYS_RUNTIME_DIR=/usr/bin/codesys/CODESYSControl/

case "$1" in
start)
	export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/bin/codesys/CODESYSControl
	cd $CODESYS_RUNTIME_DIR
	./codesyscontrol > $LOGFILE 2>&1 &

	sleep 1 && pgrep codesyscontrol > /dev/null && echo "codesyscontrol started" || echo "ERROR: codesyscontrol not started!";
	;;
stop)
	echo "stopping codesys"
	killall codesyscontrol
	echo "stopping done"
	;;
*)
	echo "usage: $0 [start|stop]"
	;;
esac

