/**
 * !!! THIS FILE IS AUTOGENERATED !!!
 *
 * This file will be overwritten with the target definitions
 * of the customer upon delivery. So, don't modify this file
 * directly!
 */

#ifndef __TARGETDEFINES_H_
#define __TARGETDEFINES_H_

#ifndef SYSTARGET_SIGNATUREID
	#define SYSTARGET_SIGNATUREID 0x76FB1D7D
#endif

#ifndef SYSTARGET_DEVICE_TYPE
	#define SYSTARGET_DEVICE_TYPE 4096
#endif

#ifndef SYSTARGET_VENDOR_ID
	#define SYSTARGET_VENDOR_ID   0x163f
#endif

#ifndef SYSTARGET_DEVICE_ID
	#define SYSTARGET_DEVICE_ID   0x0001
#endif

#ifndef SYSTARGET_DEVICE_MASK
	#define SYSTARGET_DEVICE_MASK 0x0000
#endif

#ifndef SYSTARGET_VENDOR_NAME
	#define SYSTARGET_VENDOR_NAME "EMICON"
#endif

#ifndef SYSTARGET_DEVICE_NAME
	#define SYSTARGET_DEVICE_NAME "EMICON-ARM Cortex-A8-Linux"
#endif

#ifndef SYSTARGET_DEVICE_VERSION
	#define SYSTARGET_DEVICE_VERSION 0x03050d0a
#endif

/*#ifndef TRG_CORTEX
	#define TRG_CORTEX
#endif*/

#endif /* __TARGETDEFINES_H_ */
